name: 'my_test_project'
version: '1.0.0'
config-version: 2

profile: 'testing_profile' # This must match the name in your profiles.yml

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_test_project:
    example:
      +materialized: view